(function(root){
'use strict';
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function money(v){return v===null||v===undefined||v===''||!Number.isFinite(Number(v))?'—':'$'+Number(v).toFixed(2);}
function productFor(rec){if(!rec)return null;if(rec.category==='DRIVER')return (root.GAL_DRIVERS||[]).find(x=>(x.canonicalProductId||x.id)===rec.canonicalProductId)||null;return (root.GALFairwayHybridData||[]).find(x=>x.product_id===rec.canonicalProductId)||null;}
function mediaFor(rec){const r=productFor(rec),m=rec&&rec.category==='DRIVER'?root.GALDriverMedia:root.GALFairwayHybridMedia;return r&&m&&m.picture?m.picture(r):{available:false,label:'Image coming soon'};}
function image(rec){const m=mediaFor(rec);return m.available?'<img loading="lazy" src="'+esc(m.src)+'"'+(m.srcset?' srcset="'+esc(m.srcset)+'" sizes="'+esc(m.sizes)+'"':'')+' alt="'+esc(m.alt)+'">':'<div class="rec-image-hold" role="img" aria-label="Product image unavailable">Image coming soon</div>';}
function card(rec,rank){const p=productFor(rec);if(!p)return '';const brand=p.brand||'',model=p.model||'',price=p.priceUSD??p.current_price_usd??null,meta=rec.category==='DRIVER'?'Driver':((p.club||'')+' · '+(p.loft_deg??'—')+'°');return '<article class="rec-card" data-id="'+esc(rec.canonicalProductId)+'"><div class="rec-rank">'+(rank===0?'Best Match':'Alternative '+rank)+'</div>'+image(rec)+'<div class="rec-score"><strong>'+rec.score+'</strong><span>GAL Fit</span></div><h3>'+esc(brand+' '+model)+'</h3><p class="rec-meta">'+esc(meta)+' · '+money(price)+'</p><p>'+esc(rec.reasons[0]||'Strong profile match.')+'</p><details><summary>Why this fits your profile</summary><ul>'+rec.reasons.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>'+(rec.tradeoffs.length?'<p><strong>Trade-off:</strong> '+esc(rec.tradeoffs.join(' '))+'</p>':'')+'</details><div class="rec-actions"><button data-action="compare">Compare</button><button data-action="bag">Add to Bag</button></div></article>';}
function bagAdapter(){return root.GALBagAdapter||{load:()=>{try{return JSON.parse(localStorage.getItem('gal_equipment_bag_v1')||'[]')}catch(e){return[]}},save:b=>localStorage.setItem('gal_equipment_bag_v1',JSON.stringify(b))};}
function add(rec){const p=productFor(rec);if(!p)return 'Unavailable';let bag=bagAdapter().load()||[];if(bag.some(x=>x.product_id===rec.canonicalProductId))return 'Already in Bag';if(bag.length>=14)return 'Bag full (14)';const cat=rec.category;if(bag.some(x=>x.category===cat)&&!confirm('You already have a '+cat.toLowerCase()+' saved. Add another?'))return 'Add to Bag';bag.push({product_id:rec.canonicalProductId,category:cat,brand:p.brand,model:p.model,club:p.club||'Driver'});bagAdapter().save(bag);return 'Added';}
async function mount(){const host=document.getElementById('recommendationApp');if(!host)return;const state=await root.GALRecommendationProfile.load(),data=root.GALRecommendationEngine.recommendations(state.snapshot);let mode='needs',category='DRIVER',compared=[];
  const banner=document.getElementById('profileSource');banner.textContent=state.preview?'Staging preview profile — connect/login to use your governed UX10 profile.':'Using governed UX10 Profile revision '+(state.snapshot.revision??'—')+'.';banner.className=state.preview?'profile-source preview':'profile-source live';
  function lookup(id){for(const n of data.needs){const x=n.items.find(i=>i.canonicalProductId===id);if(x)return x;}for(const arr of Object.values(data.categories)){const x=arr.find(i=>i.canonicalProductId===id);if(x)return x;}return null;}
  function draw(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));const categoryNav=document.getElementById('categoryNav');categoryNav.hidden=mode!=='categories';
    let html='';if(mode==='needs')data.needs.forEach(n=>{html+='<section class="need"><div class="need-head"><div><span class="eyebrow">Bag need</span><h2>'+esc(n.label)+'</h2><p>'+esc(n.summary)+'</p></div></div><div class="rec-grid">'+n.items.map(card).join('')+'</div></section>';});else{const arr=data.categories[category]||[];html='<section class="need"><div class="need-head"><div><span class="eyebrow">Equipment category</span><h2>'+esc(category==='DRIVER'?'Drivers':category==='FAIRWAY'?'Fairway Woods':'Hybrids')+'</h2><p>Ranked from the same Profile-driven engine.</p></div></div><div class="rec-grid">'+arr.slice(0,12).map(card).join('')+'</div></section>';}
    host.innerHTML=html;document.getElementById('compareTray').innerHTML=compared.length?compared.map(x=>{const p=productFor(x);return p?'<span>'+esc(p.brand+' '+p.model)+'</span>':'';}).join(''):'Select up to three recommendations to compare.';}
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;draw();});document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;draw();});host.onclick=e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;const rec=lookup(btn.closest('[data-id]').dataset.id);if(!rec)return;if(btn.dataset.action==='compare'){if(compared.some(x=>x.canonicalProductId===rec.canonicalProductId))compared=compared.filter(x=>x.canonicalProductId!==rec.canonicalProductId);else if(compared.length<3)compared.push(rec);draw();}else btn.textContent=add(rec);};draw();}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',mount);
root.GALRecommendationApp=Object.freeze({mount,money,productFor,mediaFor,add});
})(typeof window!=='undefined'?window:globalThis);