(function(){
 const $=id=>document.getElementById(id),authStatus=$('authStatus'),bagStatus=$('driverBagStatus'),bagState=$('bagState');
 function safe(v){try{return JSON.stringify(v,null,2)}catch(e){return String(v)}}
 async function checkSession(){const u=await window.GALRemote.getSessionUser();authStatus.textContent=u?('SIGNED IN · '+(u.email||u.id)):'SIGNED OUT';return u}
 async function signIn(){const c=window.GALRemote.ready();if(!c)throw new Error('Supabase client unavailable');const email=$('email').value.trim(),password=$('password').value;const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;await checkSession();return data}
 async function signOut(){await window.GALRemote.signOut();await checkSession();bagStatus.textContent='Signed out. Sign in again to verify persistence.'}
 async function add(id){bagStatus.textContent='Saving '+id+' to My Bag…';const result=await window.GALDriverRC15.addToBag(id);if(result&&result.ok){const warnings=result.warningState&&Array.isArray(result.warningState.warnings)?result.warningState.warnings:[];const warningText=warnings.map(w=>w&&w.message?w.message:String(w)).filter(Boolean).join(' ');bagStatus.textContent=result.local?'Saved locally for this browser. Sign in to sync My GAL.':('Saved to My GAL.'+(warningText?' '+warningText:''));bagStatus.className='status '+(warningText?'warn':'pass')}else{if(result&&result.code==='SLOT_CONFLICT')bagStatus.textContent='A Driver is already active in My Bag. Open My Bag to review or replace it.';else bagStatus.textContent='My Bag save did not complete'+(result&&result.code?': '+result.code:'')+'.';bagStatus.className='status warn'}return result}
 async function warnings(){const r=await window.GALDriverRC15.refreshBagWarnings();bagStatus.textContent=safe(r);return r}
 async function loadBag(){const r=await window.GALRemote.loadBag();bagState.textContent=safe(r);return r}
 $('signIn').onclick=()=>signIn().catch(e=>authStatus.textContent='ERROR · '+e.message);$('signOut').onclick=()=>signOut().catch(e=>authStatus.textContent='ERROR · '+e.message);$('session').onclick=()=>checkSession().catch(e=>authStatus.textContent='ERROR · '+e.message);$('addPrimary').onclick=()=>add('GAL-DRV-0003').catch(e=>bagStatus.textContent='ERROR · '+e.message);$('addSecond').onclick=()=>add('GAL-DRV-0002').catch(e=>bagStatus.textContent='ERROR · '+e.message);$('warnings').onclick=()=>warnings().catch(e=>bagStatus.textContent='ERROR · '+e.message);$('loadBag').onclick=()=>loadBag().catch(e=>bagState.textContent='ERROR · '+e.message);window.__RC15_ACCEPTANCE={checkSession,signIn,signOut,add,warnings,loadBag};checkSession().catch(()=>{});
})();
