(function(){
 const $=id=>document.getElementById(id),authStatus=$('authStatus'),bagStatus=$('driverBagStatus'),bagState=$('bagState');
 function safe(v){try{return JSON.stringify(v,null,2)}catch(e){return String(v)}}
 function makeCredentials(){const bytes=new Uint8Array(12);crypto.getRandomValues(bytes);const hex=[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');$('email').value='rc15-ui-'+hex.slice(0,12)+'@example.com';$('password').value='Rc15!'+hex+'Aa7';authStatus.textContent='Synthetic credentials generated in this browser only.';return {email:$('email').value,password:$('password').value}}
 async function checkSession(){const u=await window.GALRemote.getSessionUser();authStatus.textContent=u?('SIGNED IN · '+(u.email||u.id)+' · '+u.id):'SIGNED OUT';return u}
 async function signUp(){const c=window.GALRemote.ready();if(!c)throw new Error('Supabase client unavailable');const email=$('email').value.trim(),password=$('password').value;if(!email||!password)throw new Error('Generate or enter synthetic credentials first.');const {data,error}=await c.auth.signUp({email,password,options:{data:{rc15_browser_acceptance:true}}});if(error)throw error;const session=!!data.session;authStatus.textContent='ACCOUNT CREATED · '+email+' · user '+(data.user?.id||'unknown')+' · session '+(session?'ACTIVE':'PENDING EMAIL CONFIRMATION');return data}
 async function signIn(){const c=window.GALRemote.ready();if(!c)throw new Error('Supabase client unavailable');const email=$('email').value.trim(),password=$('password').value;const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;await checkSession();return data}
 async function signOut(){await window.GALRemote.signOut();await checkSession();bagStatus.textContent='Signed out. Sign in again to verify persistence.'}
 async function loadBag(){const r=await window.GALRemote.loadBag();bagState.textContent=safe(r);return r}
 async function seed14(){const c=window.GALRemote.ready(),u=await window.GALRemote.getSessionUser();if(!c||!u)throw new Error('Sign in first.');const current=await loadBag();const active=(current?.items||[]).filter(x=>x.itemType==='CLUB'&&x.status==='IN_BAG'&&x.countsToward14);if(active.length)throw new Error('Fixture refused: bag already contains '+active.length+' active clubs.');const slots=['3W','5W','3H','4H','5H','4i','5i','6i','7i','8i','9i','PW','SW','P'];const payload={canonicalProductId:'GAL-IRN-0001',status:'IN_BAG',displaySnapshot:{brand:'GAL Acceptance',model:'14-club synthetic fixture'},configuration:{acceptanceFixture:true},components:slots.map(s=>({slotCode:s,slotLabel:s,clubCount:1,configuration:{acceptanceFixture:true}})),decision:{sourceTool:'rc15_browser_acceptance_fixture',sourceToolVersion:'1.0',recommendationRank:null,userInputs:{synthetic:true},metrics:{fixtureClubCount:14},reasonSummary:'Synthetic 14-club browser acceptance fixture',marketCode:'US'}};const {data,error}=await c.rpc('gal_add_to_my_bag',{p_payload:payload});if(error)throw error;bagState.textContent=safe(data);return data}
 async function add(id){bagStatus.textContent='Saving '+id+' to My Bag…';const result=await window.GALDriverRC15.addToBag(id);if(result&&result.ok){const warnings=result.warningState&&Array.isArray(result.warningState.warnings)?result.warningState.warnings:[];const warningText=warnings.map(w=>w&&w.message?w.message:String(w)).filter(Boolean).join(' ');bagStatus.textContent=result.local?'Saved locally for this browser. Sign in to sync My GAL.':('Saved to My GAL.'+(warningText?' '+warningText:''));bagStatus.className='status '+(warningText?'warn':'pass')}else{if(result&&result.code==='SLOT_CONFLICT')bagStatus.textContent='A Driver is already active in My Bag. Open My Bag to review or replace it.';else bagStatus.textContent='My Bag save did not complete'+(result&&result.code?': '+result.code:'')+'.';bagStatus.className='status warn'}return result}
 async function warnings(){const r=await window.GALDriverRC15.refreshBagWarnings();bagStatus.textContent=safe(r);return r}
 $('generate').onclick=()=>makeCredentials();$('signUp').onclick=()=>signUp().catch(e=>authStatus.textContent='ERROR · '+e.message);$('signIn').onclick=()=>signIn().catch(e=>authStatus.textContent='ERROR · '+e.message);$('signOut').onclick=()=>signOut().catch(e=>authStatus.textContent='ERROR · '+e.message);$('session').onclick=()=>checkSession().catch(e=>authStatus.textContent='ERROR · '+e.message);$('seed14').onclick=()=>seed14().catch(e=>bagState.textContent='ERROR · '+e.message);$('addPrimary').onclick=()=>add('GAL-DRV-0003').catch(e=>bagStatus.textContent='ERROR · '+e.message);$('addSecond').onclick=()=>add('GAL-DRV-0002').catch(e=>bagStatus.textContent='ERROR · '+e.message);$('warnings').onclick=()=>warnings().catch(e=>bagStatus.textContent='ERROR · '+e.message);$('loadBag').onclick=()=>loadBag().catch(e=>bagState.textContent='ERROR · '+e.message);window.__RC15_ACCEPTANCE={makeCredentials,checkSession,signUp,signIn,signOut,seed14,add,warnings,loadBag};checkSession().catch(()=>{});
})();
