-- GI-1.1 Foundation Task 6
-- Purpose: seed the minimal QUESTION-1.0 vocabulary required for shared golfer-memory flows.
-- Generated with Supabase CLI 2.116.0: supabase migration new gi11_seed_questions

insert into public.gal_question_catalog (
  question_key,
  question_version,
  status,
  question_text,
  short_label,
  help_text,
  why_gal_asks,
  response_type,
  primary_fact_key,
  secondary_fact_keys,
  category,
  domain,
  required_level,
  can_skip,
  allow_unknown,
  proxy_group,
  refresh_class,
  confidence_rule,
  branching_rule,
  output_type,
  commercial_class
) values
  (
    'game.handicap_index',
    'QUESTION-1.0',
    'ACTIVE',
    'What is your current Handicap Index?',
    'Handicap Index',
    'If you do not know it, you can skip this and GAL can use other game-level information.',
    'Handicap helps GAL calibrate forgiveness, consistency, and performance expectations across equipment categories.',
    'NUMBER',
    'game.handicap_index',
    '[]'::jsonb,
    null,
    'game',
    'CRITICAL',
    true,
    true,
    null,
    'dynamic',
    '{"source_type":"DECLARED","default_confidence":1.0}'::jsonb,
    '{}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  ),
  (
    'swing.iron_7.carry_yards',
    'QUESTION-1.0',
    'ACTIVE',
    'What is your typical 7-iron carry?',
    '7-Iron Carry',
    'Use carry distance, not total distance. An estimate is fine.',
    '7-iron carry helps GAL understand iron speed, launch needs, gapping, and suitable club categories.',
    'NUMBER',
    'swing.iron_7.carry_yards',
    '[]'::jsonb,
    'IRON',
    'swing',
    'CRITICAL',
    true,
    true,
    null,
    'dynamic',
    '{"source_type":"DECLARED","default_confidence":0.90}'::jsonb,
    '{}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  ),
  (
    'swing.driver.speed_mph',
    'QUESTION-1.0',
    'ACTIVE',
    'What is your driver swing speed?',
    'Driver Swing Speed',
    'Use a measured number if you know it. If you do not, choose “I don’t know” and GAL will use an approved distance proxy.',
    'Driver speed is a high-value fitting input for launch, spin, loft, shaft, and forgiveness decisions.',
    'NUMBER',
    'swing.driver.speed_mph',
    '[]'::jsonb,
    'DRIVER',
    'swing',
    'CRITICAL',
    true,
    true,
    'driver_speed_estimation',
    'dynamic',
    '{"source_type":"DECLARED","default_confidence":0.90}'::jsonb,
    '{"when_unknown":{"next_question_key":"swing.driver.carry_yards","proxy_group":"driver_speed_estimation"}}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  ),
  (
    'swing.driver.carry_yards',
    'QUESTION-1.0',
    'ACTIVE',
    'What is your typical driver carry?',
    'Driver Carry',
    'Use carry distance, not total distance. A reasonable estimate is useful.',
    'Driver carry can stand in as an approved proxy when measured swing speed is unknown.',
    'NUMBER',
    'swing.driver.carry_yards',
    '[]'::jsonb,
    'DRIVER',
    'swing',
    'CRITICAL',
    true,
    true,
    'driver_speed_estimation',
    'dynamic',
    '{"source_type":"DECLARED","default_confidence":0.85}'::jsonb,
    '{}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  ),
  (
    'swing.driver.typical_miss',
    'QUESTION-1.0',
    'ACTIVE',
    'What is your most common driver miss?',
    'Typical Driver Miss',
    'Choose the miss you most want your equipment to help manage.',
    'Typical miss direction helps GAL prioritize forgiveness and directional fit rather than assuming all misses are the same.',
    'SINGLE_SELECT',
    'swing.driver.typical_miss',
    '[]'::jsonb,
    'DRIVER',
    'swing',
    'HELPFUL',
    true,
    true,
    null,
    'dynamic',
    '{"source_type":"DECLARED","default_confidence":0.90}'::jsonb,
    '{}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  ),
  (
    'goal.equipment_priority',
    'QUESTION-1.0',
    'ACTIVE',
    'What do you most want your equipment to improve right now?',
    'Equipment Priority',
    'Choose the outcome that matters most to you today.',
    'Your current priority lets GAL distinguish between equally good products that solve different golfer problems.',
    'SINGLE_SELECT',
    'goal.equipment_priority',
    '[]'::jsonb,
    null,
    'goals',
    'HELPFUL',
    true,
    true,
    null,
    'event_driven',
    '{"source_type":"DECLARED","default_confidence":1.0}'::jsonb,
    '{}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  ),
  (
    'preference.value.price_sensitivity',
    'QUESTION-1.0',
    'ACTIVE',
    'How much should price influence your recommendation?',
    'Price Sensitivity',
    'GAL can favor lower-priced options when fit is otherwise comparable.',
    'Price belongs in golfer-specific value scoring only. It never allows affiliate economics to influence recommendation rank.',
    'SINGLE_SELECT',
    'preference.value.price_sensitivity',
    '[]'::jsonb,
    null,
    'value',
    'HELPFUL',
    true,
    true,
    null,
    'seasonal',
    '{"source_type":"DECLARED","default_confidence":1.0}'::jsonb,
    '{}'::jsonb,
    'PROFILE_FACT',
    'aggregate_eligible'
  )
on conflict (question_key, question_version) do update set
  status = excluded.status,
  question_text = excluded.question_text,
  short_label = excluded.short_label,
  help_text = excluded.help_text,
  why_gal_asks = excluded.why_gal_asks,
  response_type = excluded.response_type,
  primary_fact_key = excluded.primary_fact_key,
  secondary_fact_keys = excluded.secondary_fact_keys,
  category = excluded.category,
  domain = excluded.domain,
  required_level = excluded.required_level,
  can_skip = excluded.can_skip,
  allow_unknown = excluded.allow_unknown,
  proxy_group = excluded.proxy_group,
  refresh_class = excluded.refresh_class,
  confidence_rule = excluded.confidence_rule,
  branching_rule = excluded.branching_rule,
  output_type = excluded.output_type,
  commercial_class = excluded.commercial_class,
  updated_at = now();
